"""OpsAgent — general DevOps orchestration across multiple toolchains."""

import uuid
from typing import Dict, Any, List
from tenacity import retry, stop_after_attempt, wait_exponential
from cybernetics.agents.base import AgentTemplate
from cybernetics.logging.logger import get_logger

logger = get_logger("cybernetics.agents.ops")


class OpsAgent(AgentTemplate):
    name = "ops"
    description = "OpsAgent: observe → diagnose → act → notify → learn"
    adapters = ["datadog", "slack", "github", "linear", "postgres"]

    def __init__(self, registry):
        super().__init__(registry)
        self.session_id = str(uuid.uuid4())

    async def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        service = input_data.get("service", "")
        alert = input_data.get("alert", "")
        logger.info("ops_start", session=self.session_id, service=service, alert=alert)
        try:
            # Phase 1: OBSERVE
            metrics = await self._observe(service)
            # Phase 2: DIAGNOSE
            diagnosis = await self._diagnose(service, alert, metrics)
            # Phase 3: ACT
            actions = await self._act(service, diagnosis)
            # Phase 4: NOTIFY
            await self._notify(service, diagnosis, actions)
            # Phase 5: LEARN
            await self._learn(service, alert, diagnosis, actions)
            return {
                "status": "completed",
                "session_id": self.session_id,
                "diagnosis": diagnosis,
                "actions_taken": actions,
            }
        except Exception as exc:
            logger.exception("ops_failed")
            return {"status": "failed", "error": str(exc), "session_id": self.session_id}

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=10))
    async def _observe(self, service: str) -> Dict[str, Any]:
        # Get Datadog metrics + K8s pod status
        metrics = await self.registry.execute("datadog", "datadog_query_metrics", {
            "query": f"avg:{service}.request.errors{{*}}",
            "from": "now-1h",
        })
        pods = await self.registry.execute("k8s_list_pods", {
            "label_selector": f"app={service}",
        })
        return {
            "metrics": metrics.data if metrics.success else {},
            "pods": pods.data.get("pods", []) if pods.success else [],
        }

    async def _diagnose(self, service: str, alert: str, metrics: Dict[str, Any]) -> str:
        pods = metrics.get("pods", [])
        crashing = sum(1 for p in pods if p.get("status") not in ("Running", "Succeeded"))
        if crashing > 0:
            return f"Pod crash loop detected for {service} ({crashing} pods unhealthy)"
        if "memory" in alert.lower():
            return f"Memory pressure on {service}"
        if "latency" in alert.lower():
            return f"Latency spike on {service}"
        return f"General alert on {service}: {alert}"

    async def _act(self, service: str, diagnosis: str) -> List[str]:
        actions = []
        if "crash loop" in diagnosis.lower():
            # Restart deployment
            r = await self.registry.execute("k8s_restart_deployment", {"name": service})
            if r.success:
                actions.append("restarted_deployment")
        if "memory" in diagnosis.lower():
            # Scale up
            r = await self.registry.execute("k8s_scale_deployment", {"name": service, "replicas": 5})
            if r.success:
                actions.append("scaled_deployment")
        # Create Linear ticket for tracking
        r = await self.registry.execute("linear", "linear_create_issue", {
            "team_id": "TEAM_ID",  # configured per workspace
            "title": f"[Ops] {diagnosis}",
            "description": f"Auto-generated by OpsAgent session {self.session_id}",
        })
        if r.success:
            actions.append("created_ticket")
        return actions

    async def _notify(self, service: str, diagnosis: str, actions: List[str]):
        await self.registry.execute("slack", "slack_post_message", {
            "channel": "#ops-alerts",
            "text": f"OpsAgent handled alert for *{service}*\nDiagnosis: {diagnosis}\nActions: {', '.join(actions)}",
        })

    async def _learn(self, service: str, alert: str, diagnosis: str, actions: List[str]):
        await self.registry.execute("postgres", "postgres_store_pattern", {
            "pattern_signature": f"ops:{service}:{alert}",
            "diagnosis": diagnosis,
            "action": ", ".join(actions),
            "outcome": "resolved",
        })
